# Generated by Django 3.0.5 on 2023-04-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('No_of_Bedrooms', models.IntegerField()),
                ('Resale', models.IntegerField()),
                ('MaintenanceStaff', models.IntegerField()),
                ('Gymnasium', models.IntegerField()),
                ('SwimmingPool', models.IntegerField()),
                ('LandscapedGardens', models.IntegerField()),
                ('JoggingTrack', models.IntegerField()),
                ('RainWaterHarvesting', models.IntegerField()),
                ('IndoorGames', models.IntegerField()),
                ('ShoppingMall', models.IntegerField()),
                ('Intercom', models.IntegerField()),
                ('SportsFacility', models.IntegerField()),
                ('ATM', models.IntegerField()),
                ('ClubHouse', models.IntegerField()),
                ('School', models.IntegerField()),
                ('ALL_Security', models.IntegerField()),
                ('PowerBackup', models.IntegerField()),
                ('CarParking', models.IntegerField()),
                ('StaffQuarter', models.IntegerField()),
                ('Cafeteria', models.IntegerField()),
                ('MultipurposeRoom', models.IntegerField()),
                ('Hospital', models.IntegerField()),
                ('WashingMachine', models.IntegerField()),
                ('Gasconnection', models.IntegerField()),
                ('AC', models.IntegerField()),
                ('Wifi', models.IntegerField()),
                ('Children_playarea', models.IntegerField()),
                ('LiftAvailable', models.IntegerField()),
                ('BED', models.IntegerField()),
                ('VaastuCompliant', models.IntegerField()),
                ('Microwave', models.IntegerField()),
                ('GolfCourse', models.IntegerField()),
                ('TV', models.IntegerField()),
                ('DiningTable', models.IntegerField()),
                ('Sofa', models.IntegerField()),
                ('Wardrobe', models.IntegerField()),
                ('Refrigerator', models.IntegerField()),
            ],
        ),
    ]
