from django.db import models
from django.contrib.auth.models import User, auth
# Create your models here.
class property(models.Model):
    area=models.IntegerField()
    location=models.CharField(max_length=100)
    description=models.CharField(max_length=100)
    city=models.CharField(max_length=100)
    No_of_Bedrooms=models.IntegerField()
    Resale=models.BooleanField()
    MaintenanceStaff=models.BooleanField()
    Gymnasium=models.BooleanField()
    SwimmingPool=models.BooleanField()
    LandscapedGardens=models.BooleanField()
    JoggingTrack=models.BooleanField()
    RainWaterHarvesting=models.BooleanField()
    IndoorGames=models.BooleanField()
    ShoppingMall=models.BooleanField()
    Intercom=models.BooleanField()
    SportsFacility=models.BooleanField()
    ATM=models.BooleanField()
    ClubHouse=models.BooleanField()
    School=models.BooleanField()
    ALL_Security=models.BooleanField()
    PowerBackup=models.BooleanField()
    CarParking=models.BooleanField()
    StaffQuarter=models.BooleanField()
    Cafeteria=models.BooleanField()
    MultipurposeRoom=models.BooleanField()
    Hospital=models.BooleanField()
    WashingMachine=models.BooleanField()
    Gasconnection=models.BooleanField()
    AC=models.BooleanField()
    Wifi=models.BooleanField()
    Children_playarea=models.BooleanField()
    LiftAvailable=models.BooleanField()
    BED=models.BooleanField()
    VaastuCompliant=models.BooleanField()
    Microwave=models.BooleanField()
    GolfCourse=models.BooleanField()
    TV=models.BooleanField()
    DiningTable=models.BooleanField()
    Sofa=models.BooleanField()
    Wardrobe=models.BooleanField()
    Refrigerator=models.BooleanField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    longitude=models.IntegerField()
    latitude=models.IntegerField()

