from django.db import models
from django.contrib.auth.models import User, auth
# Create your models here.
class property(models.Model):
    area=models.IntegerField()
    location=models.CharField(max_length=100)
    description=models.CharField(max_length=100)
    city=models.CharField(max_length=100)
    No_of_Bedrooms=models.IntegerField()
    Resale=models.IntegerField()
    MaintenanceStaff=models.IntegerField()
    Gymnasium=models.IntegerField()
    SwimmingPool=models.IntegerField()
    LandscapedGardens=models.IntegerField()
    JoggingTrack=models.IntegerField()
    RainWaterHarvesting=models.IntegerField()
    IndoorGames=models.IntegerField()
    ShoppingMall=models.IntegerField()
    Intercom=models.IntegerField()
    SportsFacility=models.IntegerField()
    ATM=models.IntegerField()
    ClubHouse=models.IntegerField()
    School=models.IntegerField()
    ALL_Security=models.IntegerField()
    PowerBackup=models.IntegerField()
    CarParking=models.IntegerField()
    StaffQuarter=models.IntegerField()
    Cafeteria=models.IntegerField()
    MultipurposeRoom=models.IntegerField()
    Hospital=models.IntegerField()
    WashingMachine=models.IntegerField()
    Gasconnection=models.IntegerField()
    AC=models.IntegerField()
    Wifi=models.IntegerField()
    Children_playarea=models.IntegerField()
    LiftAvailable=models.IntegerField()
    BED=models.IntegerField()
    VaastuCompliant=models.IntegerField()
    Microwave=models.IntegerField()
    GolfCourse=models.IntegerField()
    TV=models.IntegerField()
    DiningTable=models.IntegerField()
    Sofa=models.IntegerField()
    Wardrobe=models.IntegerField()
    Refrigerator=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    longitude=models.IntegerField()
    latitude=models.IntegerField()

